### ISSUE TITLE
不支持直接cli调用吗

### ISSUE THREAD

**Issue by liesauer** [uikoo9/qiao-nodejs#2]

**Comment by uikoo9** [comment]
有4个包，具体指哪个

**Comment by liesauer** [comment]
`qiao-zip`这个包，我想找能在cli直接调用的包，找了好多，要么不支持，要么BUG一堆。

**Comment by uikoo9** [comment]
之前的qiao-zip包含cli，后来删除了，新开发了一个qiao-zip-cli，你看下，https://code.insistime.com/qiao-zip-cli#/
