### ISSUE TITLE
qiao-get-ip: Optional console.time

### ISSUE THREAD

**Issue by ortexx** [uikoo9/qiao-nodejs#4]
Can you add an option to disable logging of the info label? A lot of  unnecessary text goes to the logs.

**Comment by uikoo9** [comment]
Okay, in version 4.3.7, the 'debug' parameter has been added. 

By default, console.time logs will not be displayed. 

If the 'debug' parameter is passed, the logs will be shown. 

Here is an example code:
```js
// ip
const ip = await getIP(timeout);

// ip debug
const ip = await getIP(timeout, true);
```
